<?php
require_once(Mage::getModuleDir('controllers', 'Mage_CatalogSearch') . DS . 'ResultController.php');

/**
 * Class MyNamespace_Test_ResultController
 */
class MyNamespace_Test_ResultController extends Mage_CatalogSearch_ResultController
{
    /**
     * Index Action
     */
    public function indexAction()
    {
     parent::indexAction(); // TODO: Change the autogenerated stub
    }
}
