<?php

/**
 * Class OnePica_Blog_Model_Resource_Setup
 */
class OnePica_Blog_Model_Resource_Setup extends Mage_Eav_Model_Entity_Setup
{
    /*
         * Setup attributes for onepica_blog_post entity type
         * -this attributes will be saved in db if you set them
         */
    public function getDefaultEntities()
    {
        $entities = array(
                'onepica_blog_post' => array(
                        'entity_model' => 'onepica_blog/post',
                        'attribute_model' => '',
                        'table' => 'onepica_blog/post_entity',
                        'attributes' => array(
                                'title' => array(
                                        'type' => 'varchar',
                                        'backend' => '',
                                        'frontend' => '',
                                        'label' => 'Title',
                                        'input' => 'text',
                                        'class' => '',
                                        'source' => '',
                                        'global' => 0,
                                        'visible' => true,
                                        'required' => true,
                                        'user_defined' => true,
                                        'default' => '',
                                        'searchable' => false,
                                        'filterable' => false,
                                        'comparable' => false,
                                        'visible_on_front' => true,
                                        'unique' => false,
                                ),
                                'published' => array(
                                        'type' => 'int',
                                        'backend' => '',
                                        'frontend' => '',
                                        'label' => 'Published',
                                        'input' => 'int',
                                        'class' => '',
                                        'source' => '',
                                        'global' => 0,
                                        'visible' => true,
                                        'required' => true,
                                        'user_defined' => true,
                                        'default' => '',
                                        'searchable' => false,
                                        'filterable' => false,
                                        'comparable' => false,
                                        'visible_on_front' => true,
                                        'unique' => false,
                                ),
                                'intro' => array(
                                        'type' => 'text',
                                        'backend' => '',
                                        'frontend' => '',
                                        'label' => 'Intro',
                                        'input' => 'text',
                                        'class' => '',
                                        'source' => '',
                                        'global' => 0,
                                        'visible' => true,
                                        'required' => true,
                                        'user_defined' => true,
                                        'default' => '',
                                        'searchable' => false,
                                        'filterable' => false,
                                        'comparable' => false,
                                        'visible_on_front' => true,
                                        'unique' => false,
                                ),
                                'post_content' => array(
                                        'type' => 'text',
                                        'backend' => '',
                                        'frontend' => '',
                                        'label' => 'Content',
                                        'input' => 'text',
                                        'class' => '',
                                        'source' => '',
                                        'global' => 0,
                                        'visible' => true,
                                        'required' => true,
                                        'user_defined' => true,
                                        'default' => '',
                                        'searchable' => false,
                                        'filterable' => false,
                                        'comparable' => false,
                                        'visible_on_front' => true,
                                        'unique' => false,
                                ),
                                'start_publishing' => array(
                                        'type' => 'datetime',
                                        'backend' => '',
                                        'frontend' => '',
                                        'label' => 'Start Publishing',
                                        'input' => 'datetime',
                                        'class' => '',
                                        'source' => '',
                                        'global' => 0,
                                        'visible' => true,
                                        'required' => false,
                                        'user_defined' => true,
                                        'default' => '0',
                                        'nullable' => true,
                                        'searchable' => false,
                                        'filterable' => false,
                                        'comparable' => false,
                                        'visible_on_front' => true,
                                        'unique' => false,
                                ),
                                'end_publishing' => array(
                                        'type' => 'datetime',
                                        'backend' => '',
                                        'frontend' => '',
                                        'label' => 'End Publishing',
                                        'input' => 'datetime',
                                        'class' => '',
                                        'source' => '',
                                        'global' => 0,
                                        'visible' => true,
                                        'required' => false,
                                        'user_defined' => true,
                                        'default' => '0',
                                        'nullable' => true,
                                        'searchable' => false,
                                        'filterable' => false,
                                        'comparable' => false,
                                        'visible_on_front' => true,
                                        'unique' => false,
                                ),
                                'keywords' => array(
                                        'type' => 'text',
                                        'backend' => '',
                                        'frontend' => '',
                                        'label' => 'Keywords',
                                        'input' => 'text',
                                        'class' => '',
                                        'source' => '',
                                        'global' => 0,
                                        'visible' => true,
                                        'required' => false,
                                        'user_defined' => true,
                                        'default' => '',
                                        'searchable' => false,
                                        'filterable' => false,
                                        'comparable' => false,
                                        'visible_on_front' => true,
                                        'unique' => false,
                                ),
                                'description' => array(
                                        'type' => 'text',
                                        'backend' => '',
                                        'frontend' => '',
                                        'label' => 'Description',
                                        'input' => 'text',
                                        'class' => '',
                                        'source' => '',
                                        'global' => 0,
                                        'visible' => true,
                                        'required' => false,
                                        'user_defined' => true,
                                        'default' => '',
                                        'searchable' => false,
                                        'filterable' => false,
                                        'comparable' => false,
                                        'visible_on_front' => true,
                                        'unique' => false,
                                ),
                        ),
                )
        );
        return $entities;
    }
}
